on:
  workflow_dispatch:
  schedule:
    - cron: '11 * * * *'

name: Timed GitHub Action

jobs:
  timed_action:
    name: Job for timed action
    runs-on: ubuntu-latest
    
    container:
      image: rocker/tidyverse:4.2
    permissions:
      contents: write
    
    steps:
      - run: git config --system --add safe.directory '*'
      
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: main
    
      - name: Hello
        run: |
          Rscript -e "writeLines(as.character(Sys.time()), 'output.txt')"

      - name: Commit and push
        run: |
          git config --global user.name 'bpbond'
          git config --global user.email 'bondlamberty@pnnl.gov'
          git add .
          git commit -m "Automated update" || echo "No changes to commit"
          git push
